
export const REQUEST_STARTED = 'REQUEST_SUBREDDIT';
export const REQUEST_FINISHED = 'REQUEST_FINISHED';
export const REQUEST_ERROR = 'REQUEST_ERROR';
export const RECEIVE_SUBREDDIT = 'RECEIVE_SUBREDDIT';
export const RECEIVE_POPULAR_SUBREDDITS = 'RECEIVE_POPULAR_SUBREDDITS';
export const RECEIVE_MATCHING_SUBREDDITS = 'RECEIVE_MATCHING_SUBREDDITS';
